import { useMemo, useState } from "react";
import Sidebar from "../components/Sidebar";
import TopBar from "../components/TopBar";
import Editor from "../components/Editor";
import Preview from "../components/Preview";
import Terminal from "../components/Terminal";
import AIChat from "../components/AIChat";
import SearchPanel from "../components/SearchPanel";
import ProjectGenerator from "../components/ProjectGenerator";
import PackageManager from "../components/PackageManager";
import SourceControl from "../components/SourceControl";
import Settings from "../components/Settings";
import "../App.css";

const DEFAULT_FILES = {
  "index.html":`<section class="hero">
  <p class="eyebrow">OpenClaw · Eios AI Software Factory</p>
  <h1>Build production apps from a single human intent.</h1>
  <p>Planner, code generator, workflow runtime, containers, infra deployment and self-healing debug loops work together in one autonomous pipeline.</p>
  <button onclick="window.dispatchEvent(new Event('demo-run'))">Run workflow</button>
</section>
<section class="grid">
  <article>LLM Planner</article>
  <article>Code Generator</article>
  <article>Runtime Logs</article>
  <article>Deploy URL</article>
</section>`,
  "style.css":`body{margin:0;background:#06111f;color:#e5f2ff;font-family:Inter,system-ui,sans-serif}.hero{min-height:62vh;padding:64px;background:radial-gradient(circle at top left,#2563eb55,transparent 34%),linear-gradient(135deg,#08111f,#101b31);display:flex;flex-direction:column;justify-content:center}.eyebrow{color:#67e8f9;text-transform:uppercase;letter-spacing:.18em;font-size:12px}h1{max-width:820px;font-size:clamp(42px,8vw,86px);line-height:.92;margin:0 0 24px}p{max-width:690px;color:#bad3ee;font-size:18px}button{width:max-content;border:0;border-radius:999px;padding:14px 22px;background:#38bdf8;color:#04111f;font-weight:800}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;padding:24px}.grid article{padding:22px;border:1px solid #23415f;border-radius:18px;background:#0d1b2f}`,
  "script.js":`window.addEventListener('demo-run',()=>alert('Eios workflow started: frontend + backend + worker + deploy pipeline'));`,
  "api/routes.js":"export const routes = ['POST /intent','GET /logs','POST /deploy'];",
};

const TABS = [
  { id:"editor", icon:"⌘", label:"Editor" },
  { id:"preview", icon:"◈", label:"Preview" },
  { id:"terminal", icon:"▣", label:"Runtime" },
  { id:"ai", icon:"✦", label:"OpenClaw" },
  { id:"search", icon:"⌕", label:"Search" },
  { id:"packages", icon:"⬡", label:"Packages" },
  { id:"source", icon:"⑂", label:"Source" },
  { id:"settings", icon:"⚙", label:"Settings" },
];

const getFolders = (files)=>[
  ...new Set(Object.keys(files).filter((file)=>file.includes("/")).map((file)=>file.split("/")[0])),
];

export default function IDE(){
  const [drawer,setDrawer]=useState(false);
  const [tab,setTab]=useState("editor");
  const [current,setCurrent]=useState("index.html");
  const [files,setFiles]=useState(DEFAULT_FILES);
  const [logs,setLogs]=useState([
    "intent parsed → production landing page",
    "containers ready → frontend, backend, worker",
    "preview server listening → live iframe",
  ]);

  const folders = useMemo(()=>getFolders(files),[files]);
  const changedFiles = useMemo(()=>Object.keys(files),[files]);

  const preview = useMemo(()=>`<!DOCTYPE html><html><head><meta charset="UTF-8"><style>${files["style.css"]||""}</style></head><body>${files["index.html"]||""}<script>${files["script.js"]||""}</script></body></html>`,[files]);

  const createFile=()=>{
    const name=prompt("Tên file mới", "src/new-feature.js");
    if(!name) return;
    setFiles((value)=>({ ...value, [name]:"// Generated by OpenClaw\n" }));
    setCurrent(name);
    setTab("editor");
  };

  const createFolder=()=>{
    const name=prompt("Tên thư mục", "services");
    if(!name) return;
    const file=`${name}/README.md`;
    setFiles((value)=>({ ...value, [file]:`# ${name}\n` }));
    setCurrent(file);
  };

  const runPreview=()=>{
    setLogs((value)=>[`run requested → ${new Date().toLocaleTimeString()}`,...value]);
    setTab("preview");
  };

  const saveWorkspace=()=>{
    localStorage.setItem("eios-openclaw-workspace", JSON.stringify(files));
    setLogs((value)=>["workspace snapshot saved",...value]);
  };

  const exportWorkspace=()=>{
    navigator.clipboard?.writeText(JSON.stringify(files,null,2));
    setLogs((value)=>["workspace exported to clipboard",...value]);
  };

  const importWorkspace=()=>{
    const raw=prompt("Dán JSON workspace");
    if(!raw) return;
    setFiles(JSON.parse(raw));
    setLogs((value)=>["workspace imported",...value]);
  };

  const openFile=(name)=>{
    setCurrent(name);
    setTab("editor");
    setDrawer(false);
  };

  return(
    <div className="ide-shell">
      <TopBar createFile={createFile} saveWorkspace={saveWorkspace} runPreview={runPreview} exportWorkspace={exportWorkspace} importWorkspace={importWorkspace}/>

      <main className="ide-main">
        <nav className="activity-bar" aria-label="Workspace tools">
          {TABS.map((item)=>(
            <button key={item.id} className={tab===item.id?"active":""} title={item.label} onClick={()=>setTab(item.id)}>
              <span>{item.icon}</span>
            </button>
          ))}
        </nav>

        <aside className={`explorer-panel ${drawer?"open":""}`}>
          <div className="panel-heading">
            <span>Explorer</span>
            <button onClick={()=>setDrawer(false)}>×</button>
          </div>
          <Sidebar files={files} folders={folders} current={current} setCurrent={openFile} createFile={createFile} createFolder={createFolder}/>
          <div className="root-files">
            {Object.keys(files).filter((file)=>!file.includes("/")).map((file)=>(
              <button key={file} className={current===file?"selected":""} onClick={()=>openFile(file)}>📄 {file}</button>
            ))}
          </div>
        </aside>

        <section className="workbench">
          <header className="hero-strip">
            <div>
              <p>Human Intent → LLM Planner → Code Generator → Runtime → Deploy</p>
              <h1>OpenClaw autonomous IDE for Eios</h1>
            </div>
            <div className="status-card"><b>Production loop</b><span>generate → run → detect → patch → rerun</span></div>
          </header>

          <div className="editor-chrome">
            <button className="mobile-explorer" onClick={()=>setDrawer(true)}>☰ Files</button>
            <span className="file-pill">{current}</span>
            <span className="live-pill">● Live preview ready</span>
          </div>

          <div className="content-pane">
            {tab==="editor" && <Editor code={files[current]||""} setCode={(value)=>setFiles({...files,[current]:value})}/>} 
            {tab==="preview" && <Preview html={preview}/>} 
            {tab==="terminal" && <div className="runtime-pane"><Terminal/><div className="log-feed">{logs.map((line)=><div key={line}>▸ {line}</div>)}</div></div>} 
            {tab==="ai" && <AIChat/>} 
            {tab==="search" && <SearchPanel files={files} openFile={openFile}/>} 
            {tab==="packages" && <PackageManager/>} 
            {tab==="source" && <SourceControl changedFiles={changedFiles} commit={()=>setLogs(["commit staged in UI",...logs])} push={()=>setLogs(["push queued",...logs])} pull={()=>setLogs(["pull completed",...logs])}/>} 
            {tab==="settings" && <Settings/>} 
          </div>
        </section>

        <aside className="right-rail">
          <ProjectGenerator setFiles={setFiles} setCurrent={setCurrent}/>
          <div className="pipeline-card"><h3>AI-Autonomous Pipeline</h3>{["Intent analysis","Architecture selection","Container runtime","HTTPS deployment","Self-healing debug"].map((step,index)=><div className="pipeline-step" key={step}><span>{index+1}</span>{step}</div>)}</div>
        </aside>
      </main>
    </div>
  );
}
